# Generated by Django 5.2.1 on 2025-06-11 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('documents', 'Documents'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('date_lost_or_found', models.DateField()),
                ('time_lost_or_found', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed')], default='lost', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('timestamp_reported', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
