# Generated by Django 5.2.1 on 2025-06-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountsApp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
